/**************************************************************************//**
 * @file
 * @brief Device Manager DMA Definition
 ******************************************************************************
 * # License
 * <b>Copyright 2025 Silicon Laboratories, Inc. www.silabs.com</b>
 ******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 *****************************************************************************/

#include "em_device.h"
#include "sl_device_dma.h"

/***************************************************************************//**
 * @addtogroup device_dma Device Manager DMA
 * @{
 ******************************************************************************/

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_LDMAXBAR0PRSREQ0)
/// Define LDMAXBAR00_PRSREQ0 DMA signal value.
const uint32_t SL_DMA_SIGNAL_LDMAXBAR0_PRSREQ0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_LDMAXBAR0PRSREQ0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_LDMAXBAR0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_LDMAXBAR0PRSREQ1)
/// Define LDMAXBAR00_PRSREQ1 DMA Signal value.
const uint32_t SL_DMA_SIGNAL_LDMAXBAR0_PRSREQ1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_LDMAXBAR0PRSREQ1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_LDMAXBAR0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0CC0)
const uint32_t SL_DMA_SIGNAL_TIMER0_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0CC1)
const uint32_t SL_DMA_SIGNAL_TIMER0_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0CC2)
const uint32_t SL_DMA_SIGNAL_TIMER0_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER0_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER0UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1CC0)
const uint32_t SL_DMA_SIGNAL_TIMER1_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1CC1)
const uint32_t SL_DMA_SIGNAL_TIMER1_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1CC2)
const uint32_t SL_DMA_SIGNAL_TIMER1_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER1_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER1UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER1;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC0)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC1)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC2)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER2_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC3)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC3_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC3 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC4)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC4_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC4 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC5)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC5_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC5 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC6)
const uint32_t SL_DMA_SIGNAL_TIMER2_CC6_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER2CC6 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER2;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC0)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC1)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC2)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER3_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC3)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC3_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC3 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC4)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC4_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC4 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC5)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC5_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC5 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC6)
const uint32_t SL_DMA_SIGNAL_TIMER3_CC6_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER3CC6 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER3;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4CC0)
const uint32_t SL_DMA_SIGNAL_TIMER4_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER4;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4CC1)
const uint32_t SL_DMA_SIGNAL_TIMER4_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER4;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4CC2)
const uint32_t SL_DMA_SIGNAL_TIMER4_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER4;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER4_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER4UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER4;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5CC0)
const uint32_t SL_DMA_SIGNAL_TIMER5_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER5;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5CC1)
const uint32_t SL_DMA_SIGNAL_TIMER5_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER5;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5CC2)
const uint32_t SL_DMA_SIGNAL_TIMER5_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER5;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER5_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER5UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER5;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6CC0)
const uint32_t SL_DMA_SIGNAL_TIMER6_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER6;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6CC1)
const uint32_t SL_DMA_SIGNAL_TIMER6_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER6;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6CC2)
const uint32_t SL_DMA_SIGNAL_TIMER6_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER6;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER6_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER6UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER6;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7CC0)
const uint32_t SL_DMA_SIGNAL_TIMER7_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER7;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7CC1)
const uint32_t SL_DMA_SIGNAL_TIMER7_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER7;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7CC2)
const uint32_t SL_DMA_SIGNAL_TIMER7_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER7;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER7_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER7UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER7;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8CC0)
const uint32_t SL_DMA_SIGNAL_TIMER8_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER8;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8CC1)
const uint32_t SL_DMA_SIGNAL_TIMER8_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER8;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8CC2)
const uint32_t SL_DMA_SIGNAL_TIMER8_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER8;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER8_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER8UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER8;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9CC0)
const uint32_t SL_DMA_SIGNAL_TIMER9_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9CC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER9;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9CC1)
const uint32_t SL_DMA_SIGNAL_TIMER9_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9CC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER9;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9CC2)
const uint32_t SL_DMA_SIGNAL_TIMER9_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9CC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER9;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9UFOF)
const uint32_t SL_DMA_SIGNAL_TIMER9_UFOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_TIMER9UFOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_TIMER9;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERBOF)
const uint32_t SL_DMA_SIGNAL_PROTIMER_BOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERBOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC0)
const uint32_t SL_DMA_SIGNAL_PROTIMER_CC0_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC0 | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC1)
const uint32_t SL_DMA_SIGNAL_PROTIMER_CC1_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC1 | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC2)
const uint32_t SL_DMA_SIGNAL_PROTIMER_CC2_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC2 | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC3)
const uint32_t SL_DMA_SIGNAL_PROTIMER_CC3_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERCC3 | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERPOF)
const uint32_t SL_DMA_SIGNAL_PROTIMER_POF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERPOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERWOF)
const uint32_t SL_DMA_SIGNAL_PROTIMER_WOF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PROTIMERWOF | LDMAXBAR0_CH_REQSEL_SOURCESEL_PROTIMER;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C0RXDATAV)
const uint32_t SL_DMA_SIGNAL_I2C0_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C0RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C0TXBL)
const uint32_t SL_DMA_SIGNAL_I2C0_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C0TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C1RXDATAV)
const uint32_t SL_DMA_SIGNAL_I2C1_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C1RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C1TXBL)
const uint32_t SL_DMA_SIGNAL_I2C1_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C1TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C1;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C2RXDATAV)
const uint32_t SL_DMA_SIGNAL_I2C2_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C2RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C2TXBL)
const uint32_t SL_DMA_SIGNAL_I2C2_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C2TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C2;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C3RXDATAV)
const uint32_t SL_DMA_SIGNAL_I2C3_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C3RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_I2C3TXBL)
const uint32_t SL_DMA_SIGNAL_I2C3_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_I2C3TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_I2C3;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_IADC0IADC_SCAN)
const uint32_t SL_DMA_SIGNAL_IADC0_SCAN_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_IADC0IADC_SCAN | LDMAXBAR0_CH_REQSEL_SOURCESEL_IADC0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_IADC0IADC_SINGLE)
const uint32_t SL_DMA_SIGNAL_IADC0_SINGLE_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_IADC0IADC_SINGLE | LDMAXBAR0_CH_REQSEL_SOURCESEL_IADC0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_ADC0ADC_SCAN)
const uint32_t SL_DMA_SIGNAL_ADC0_SCAN_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_ADC0ADC_SCAN | LDMAXBAR0_CH_REQSEL_SOURCESEL_ADC0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_ADC1ADC_SCAN)
const uint32_t SL_DMA_SIGNAL_ADC1_SCAN_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_ADC1ADC_SCAN | LDMAXBAR0_CH_REQSEL_SOURCESEL_ADC1;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART0RXFL)
const uint32_t SL_DMA_SIGNAL_EUSART0_RXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART0RXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART0TXFL)
const uint32_t SL_DMA_SIGNAL_EUSART0_TXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART0TXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART1RXFL)
const uint32_t SL_DMA_SIGNAL_EUSART1_RXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART1RXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART1TXFL)
const uint32_t SL_DMA_SIGNAL_EUSART1_TXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART1TXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART1;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART2RXFL)
const uint32_t SL_DMA_SIGNAL_EUSART2_RXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART2RXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART2TXFL)
const uint32_t SL_DMA_SIGNAL_EUSART2_TXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART2TXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART2;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART3RXFL)
const uint32_t SL_DMA_SIGNAL_EUSART3_RXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART3RXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART3;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART3TXFL)
const uint32_t SL_DMA_SIGNAL_EUSART3_TXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART3TXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART3;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART4RXFL)
const uint32_t SL_DMA_SIGNAL_EUSART4_RXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART4RXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART4;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART4TXFL)
const uint32_t SL_DMA_SIGNAL_EUSART4_TXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUSART4TXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUSART4;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART0RXDATAV)
const uint32_t SL_DMA_SIGNAL_USART0_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART0RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART0RXDATAVRIGHT)
const uint32_t SL_DMA_SIGNAL_USART0_RXDATAVRIGHT_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART0RXDATAVRIGHT | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART0TXBL)
const uint32_t SL_DMA_SIGNAL_USART0_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART0TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART0TXBLRIGHT)
const uint32_t SL_DMA_SIGNAL_USART0_TXBLRIGHT_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART0TXBLRIGHT | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART0TXEMPTY)
const uint32_t SL_DMA_SIGNAL_USART0_TXEMPTY_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART0TXEMPTY | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART1RXDATAV)
const uint32_t SL_DMA_SIGNAL_USART1_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART1RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART1RXDATAVRIGHT)
const uint32_t SL_DMA_SIGNAL_USART1_RXDATAVRIGHT_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART1RXDATAVRIGHT | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART1TXBL)
const uint32_t SL_DMA_SIGNAL_USART1_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART1TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART1TXBLRIGHT)
const uint32_t SL_DMA_SIGNAL_USART1_TXBLRIGHT_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART1TXBLRIGHT | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART1TXEMPTY)
const uint32_t SL_DMA_SIGNAL_USART1_TXEMPTY_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART1TXEMPTY | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART1;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART2RXDATAV)
const uint32_t SL_DMA_SIGNAL_USART2_RXDATAV_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART2RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART2RXDATAVRIGHT)
const uint32_t SL_DMA_SIGNAL_USART2_RXDATAVRIGHT_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART2RXDATAVRIGHT | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART2TXBL)
const uint32_t SL_DMA_SIGNAL_USART2_TXBL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART2TXBL | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART2TXBLRIGHT)
const uint32_t SL_DMA_SIGNAL_USART2_TXBLRIGHT_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART2TXBLRIGHT | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART2;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_USART2TXEMPTY)
const uint32_t SL_DMA_SIGNAL_USART2_TXEMPTY_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_USART2TXEMPTY | LDMAXBAR0_CH_REQSEL_SOURCESEL_USART2;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUART0RXFL)
const uint32_t SL_DMA_SIGNAL_EUART0_RXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUART0RXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUART0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_EUART0TXFL)
const uint32_t SL_DMA_SIGNAL_EUART0_TXFL_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_EUART0TXFL | LDMAXBAR0_CH_REQSEL_SOURCESEL_EUART0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_MSCWDATA)
const uint32_t SL_DMA_SIGNAL_MSC_WDATA_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_MSCWDATA | LDMAXBAR0_CH_REQSEL_SOURCESEL_MSC;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC0CH0_REQ)
const uint32_t SL_DMA_SIGNAL_VDAC0_CH0REQ_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC0CH0_REQ | LDMAXBAR0_CH_REQSEL_SOURCESEL_VDAC0;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC0CH1_REQ)
const uint32_t SL_DMA_SIGNAL_VDAC0_CH1REQ_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC0CH1_REQ | LDMAXBAR0_CH_REQSEL_SOURCESEL_VDAC0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC1CH0_REQ)
const uint32_t SL_DMA_SIGNAL_VDAC1_CH0REQ_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC1CH0_REQ | LDMAXBAR0_CH_REQSEL_SOURCESEL_VDAC1;
#endif
#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC1CH1_REQ)
const uint32_t SL_DMA_SIGNAL_VDAC1_CH1REQ_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_VDAC1CH1_REQ | LDMAXBAR0_CH_REQSEL_SOURCESEL_VDAC1;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_LESENSEFIFO)
const uint32_t SL_DMA_SIGNAL_LESENSE_FIFO_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_LESENSEFIFO | LDMAXBAR0_CH_REQSEL_SOURCESEL_LESENSE;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_LCD)
const uint32_t SL_DMA_SIGNAL_LCD_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_LCD | LDMAXBAR0_CH_REQSEL_SOURCESEL_LCD;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_MVPREQ)
const uint32_t SL_DMA_SIGNAL_MVP_REQ_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_MVPREQ | LDMAXBAR0_CH_REQSEL_SOURCESEL_MVP;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PDM0RXDATAV)
const uint32_t SL_DMA_SIGNAL_PDM0_RXDATA_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PDM0RXDATAV | LDMAXBAR0_CH_REQSEL_SOURCESEL_PDM0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PIXELRZ0REQ_TXF)
const uint32_t SL_DMA_SIGNAL_PIXELRZ0REQ_TXF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PIXELRZ0REQ_TXF | LDMAXBAR0_CH_REQSEL_SOURCESEL_PIXELRZ0;
#endif

#if defined(LDMAXBAR0_CH_REQSEL_SIGSEL_PIXELRZ1REQ_TXF)
const uint32_t SL_DMA_SIGNAL_PIXELRZ1REQ_TXF_VALUE = LDMAXBAR0_CH_REQSEL_SIGSEL_PIXELRZ1REQ_TXF | LDMAXBAR0_CH_REQSEL_SOURCESEL_PIXELRZ1;
#endif

/** @} (end addtogroup device_dma) */
