#!/usr/bin/env python3

"""
Copyright (c) 2025 Silicon Laboratories Inc.

SPDX-License-Identifier: Apache-2.0
"""
import argparse
import re
import datetime
from pathlib import Path

import util.copyright_header

devices = {
  "xg21": {
    "bits": "platform/Device/SiliconLabs/EFR32MG21/Include/efr32mg21_acmp.h",
  },
  "xg23": {
    "bits": "platform/Device/SiliconLabs/EFR32FG23/Include/efr32fg23_acmp.h",
  },
  "xg24": {
    "bits": "platform/Device/SiliconLabs/EFR32MG24/Include/efr32mg24_acmp.h",
  },
  "xg26": {
      "bits": "platform/Device/SiliconLabs/EFR32MG26/Include/efr32mg26_acmp.h",
  },
  "xg27": {
    "bits": "platform/Device/SiliconLabs/EFR32BG27/Include/efr32bg27_acmp.h",
  },
  "xg28": {
      "bits": "platform/Device/SiliconLabs/EFR32ZG28/Include/efr32zg28_acmp.h",
  },
  "xg29": {
    "bits": "platform/Device/SiliconLabs/EFR32MG29/Include/efr32mg29_acmp.h",
  },
}

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="Generate headers for Comparator for Series 2 "
                                   "devices. The headers are used from DeviceTree, and represent "
                                   "every ACMP input selection as a DT compatible macro.")
  parser.add_argument("--out", "-o", type=Path, default=Path(__file__).parent / "out",
                      help="Output directory. Defaults to the directory ./out/ relative to the "
                      "script. Set to $ZEPHYR_BASE/include/zephyr/dt-bindings/comparator/ "
                      "to directly generate output into the expected location within the Zephyr "
                      "main tree.")
  parser.add_argument("--sdk", "-s", type=Path, default=Path(__file__).parent.parent / "simplicity_sdk",
                      help="Path to Simplicity SDK to extract data from. Defaults to the directory "
                       "../simplicity_sdk relative to the script.")
  args = parser.parse_args()

  args.out.mkdir(exist_ok=True)

  defines = {}
  for device, data_sources in devices.items():
    bits_file = (args.sdk / data_sources["bits"]).resolve()
    with bits_file.open() as f:
      for line in f:

        if m := re.match(r"#define (_ACMP_INPUTCTRL_(?:POS|NEG)SEL_(?!SHIFT)(?!MASK)(?!DEFAULT).*)\s+(\dx[\dABCDEF]+)", line):
          input_value = hex(int(m.group(2),16))
          input_name = f"#define ACMP_INPUT_{m.group(1).split('_')[-1]}"
          # Detect any input definition collisions
          existing_name = next((k for k, v in defines.items() if v == input_value), None)
          if existing_name and existing_name != input_name:
                print(f"{input_name.strip()} and {existing_name.strip()} share the same value {input_value}.")
          defines.update({input_name: input_value})

  # Sort defines by key
  defines = dict(sorted(defines.items(), key=lambda e: e[1]))

  lines = [
    f"#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_COMPARATOR_SILABS_ACMP_H_",
    f"#define ZEPHYR_INCLUDE_DT_BINDINGS_COMPARATOR_SILABS_ACMP_H_",
    "",
    f"/* ACMP Input Definitions */",
  ] + list(f"{k} {v}" for k, v in defines.items()) + [
    "",
    f"#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_COMPARATOR_SILABS_ACMP_H_ */",
    "",
  ]

  description = [
    f"This file was generated by the script {Path(__file__).name} in the hal_silabs module.",
    "Do not manually edit.",
  ]

  outfile = args.out / f"silabs-acmp.h"
  header = util.copyright_header.from_path(outfile, description)
  content = header + "\n".join(lines)
  outfile.write_text(content)
